### ISSUE TITLE
Nil value causing an error

### ISSUE THREAD

**Issue by xianthe** [xurion/ffxi-random-mount#6]
![image](https://user-images.githubusercontent.com/279276/140408471-b25872b4-5625-4503-b337-d3a821f07882.png)

I added a check to make sure ki has a value as a workaround (line 52):

```
       if (ki ~= nil) then
          if ki.category == 'Mounts' and ki.name ~= "trainer's whistle" then -- Don't care about the quest KI
            local mount_index = possible_mounts:find(function(possible_mount)
                return windower.wc_match(ki.name:lower(), '♪' .. possible_mount .. '*')
            end)
            local mount = possible_mounts[mount_index]

            allowed_mounts_set:add(mount)
          end
        end
```

**Comment by xurion** [comment]
Thanks! Not sure if you know, but the reason this happens is because SE mess up their key item IDs. This happened once with a mount a while ago where the new mount had the same ID as another KI. Would you be willing to submit a PR with this?

**Comment by xurion** [comment]
Thanks for the PR and the edit! I've merged it now and will bump the version. I have an [existing PR](https://github.com/Windower/Lua/pull/2090) waiting to go into Windower so I'll update that request to contain this next version.
